### ISSUE TITLE
Unable to get color mesh

### ISSUE THREAD

**Issue by manthan99** [VIS4ROB-lab/voxblox_multi_agent#1]
Hi

I am trying to run this package for multi-robot mapping but I am only able to get a grayscale mesh. Despite changing the Voxblox color_mode parameter to "color", I am still getting a gray voxblox mesh.
Please let me know, what should the parameter be set to in order to get a colored mesh

I am using the multi-robot simulation package from the multi-robot coordination repo.

EDIT:
It seems this is the issue due to the VI_sensor plugin which seems to be generating only gray images. Could you please confirm this? Also is there any VI sensor plugin that gives colored point clouds?

Thankyou

**Comment by lucaBartolomei** [comment]
Hi,

thanks for the interest in the repo. 

The parameter you are changing is the correct one (API [here](https://voxblox.readthedocs.io/en/latest/pages/The-Voxblox-Node.html#parameters)) - you could test it for example showing the mesh normals instead of the color.
However, as you said, voxblox is able to produce colored meshes if you provide color point clouds as input. At the moment, the point cloud we get from simulation carries no color information and I am not aware of a [RotorS plugin](https://github.com/ethz-asl/rotors_simulator) that can produce colored point cloud.

If you really need a colored point cloud, you could mount two color cameras on the UAV (e.g. changing the definition of the VI-sensor to generate color images), generate a disparity image out of those and map the pixel colors from the original images to the disparity image. But honestly, this is a lot of work to gain basically nothing but a nicer visualization. If you want to go down this road, the RotorS repo is the one to check.

Hopefully this helps. I will close this issue as it is not directly related to the repo. Feel free to re-open it in case.
